In [50]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [51]:
df= pd.read_excel('Windfarm.xlsx')
df.head()

,Time(year-month-day h:m:s),Wind speed at height of 10 meters (m/s),Wind direction at height of 10 meters (˚),Wind speed at height of 30 meters (m/s),Wind direction at height of 30 meters (˚),Wind speed at height of 50 meters (m/s),Wind direction at height of 50 meters (˚),Wind speed - at the height of wheel hub (m/s),Wind speed - at the height of wheel hub (˚),Air temperature (°C),Atmosphere (hpa),Relative humidity (%),Power (MW)
0,2019-01-01 00:00:00,2.209,81.317,1.991,74.814,2.094,77.667,2.494,74.500,-13.484,889.867,76.320,0.254383
1,2019-01-01 00:15:00,1.828,77.460,1.698,75.048,1.757,88.733,1.882,74.367,-13.691,889.575,76.757,0.329703
2,2019-01-01 00:30:00,2.193,86.700,2.313,84.688,2.344,89.100,2.350,89.000,-13.766,889.942,76.981,0.296306
3,2019-01-01 00:45:00,2.654,78.160,2.494,74.939,2.574,87.267,2.808,82.733,-13.691,889.675,76.821,0.187590
4,2019-01-01 01:00:00,2.249,94.297,2.192,91.140,2.558,96.900,2.924,92.967,-13.447,890.025,74.571,0.081005

In [52]:
#Checking for null values
df.isnull().any()

Time(year-month-day h:m:s)                       False
Wind speed at height of 10 meters (m/s)          False
Wind direction at height of 10 meters (˚)        False
Wind speed at height of 30 meters (m/s)          False
Wind direction at height of 30 meters (˚)        False
Wind speed at height of 50 meters (m/s)          False
Wind direction at height of 50 meters (˚)        False
Wind speed - at the height of wheel hub (m/s)    False
Wind speed - at the height of wheel hub (˚)      False
Air temperature (°C)                             False
Atmosphere (hpa)                                 False
Relative humidity (%)                            False
Power (MW)                                       False
dtype: bool

In [53]:
#Creating a copy of the dataframe
dfcpy=df.copy()
dfcpy

,Time(year-month-day h:m:s),Wind speed at height of 10 meters (m/s),Wind direction at height of 10 meters (˚),Wind speed at height of 30 meters (m/s),Wind direction at height of 30 meters (˚),Wind speed at height of 50 meters (m/s),Wind direction at height of 50 meters (˚),Wind speed - at the height of wheel hub (m/s),Wind speed - at the height of wheel hub (˚),Air temperature (°C),Atmosphere (hpa),Relative humidity (%),Power (MW)
0,2019-01-01 00:00:00,2.209,81.317,1.991,74.814,2.094,77.667,2.494,74.500,-13.484,889.867,76.320,0.254383
1,2019-01-01 00:15:00,1.828,77.460,1.698,75.048,1.757,88.733,1.882,74.367,-13.691,889.575,76.757,0.329703
2,2019-01-01 00:30:00,2.193,86.700,2.313,84.688,2.344,89.100,2.350,89.000,-13.766,889.942,76.981,0.296306
3,2019-01-01 00:45:00,2.654,78.160,2.494,74.939,2.574,87.267,2.808,82.733,-13.691,889.675,76.821,0.187590
4,2019-01-01 01:00:00,2.249,94.297,2.192,91.140,2.558,96.900,2.924,92.967,-13.447,890.025,74.571,0.081005
...,...,...,...,...,...,...,...,...,...,...,...,...,...
70171,2020-12-31 22:45:00,5.738,234.600,6.408,235.454,6.575,242.033,6.680,238.433,-9.108,890.008,53.312,13.633642
70172,2020-12-31 23:00:00,5.748,229.333,6.231,233.423,6.372,239.800,6.448,236.833,-9.978,889.817,53.877,6.869759
70173,2020-12-31 23:15:00,4.468,235.133,4.406,253.261,4.381,263.400,4.399,261.733,-9.808,889.825,54.437,4.352931
70174,2020-12-31 23:30:00,3.730,242.580,3.280,252.492,3.204,268.600,3.446,266.733,-9.633,889.492,54.677,7.185250
70175,2020-12-31 23:45:00,3.291,243.733,3.311,254.267,3.643,266.733,4.306,268.633,-8.991,889.492,53.381,12.384466

In [54]:
#renaming a column name
dfcpy.rename(columns = {'Power (MW)':'Power'}, inplace = True)
dfcpy.rename(columns={'Time(year-month-day h:m:s)':'Time'},inplace = True)
dfcpy.rename(columns={'Wind speed at height of 10 meters (m/s)':'Windspeed10m'},inplace = True)
dfcpy.rename(columns={'Wind direction at height of 10 meters (˚)':'Winddir10'},inplace = True)
dfcpy.rename(columns={'Wind speed - at the height of wheel hub (˚)':'Wind direction - at the height of wheel hub (˚)'},inplace = True)
dfcpy.rename(columns={'Wind speed at height of 30 meters (m/s)':'Windspeed30m'},inplace = True)
dfcpy.rename(columns={'Wind direction at height of 30 meters (˚)':'Winddir30'},inplace = True)
dfcpy

,Time,Windspeed10m,Winddir10,Windspeed30m,Winddir30,Wind speed at height of 50 meters (m/s),Wind direction at height of 50 meters (˚),Wind speed - at the height of wheel hub (m/s),Wind direction - at the height of wheel hub (˚),Air temperature (°C),Atmosphere (hpa),Relative humidity (%),Power
0,2019-01-01 00:00:00,2.209,81.317,1.991,74.814,2.094,77.667,2.494,74.500,-13.484,889.867,76.320,0.254383
1,2019-01-01 00:15:00,1.828,77.460,1.698,75.048,1.757,88.733,1.882,74.367,-13.691,889.575,76.757,0.329703
2,2019-01-01 00:30:00,2.193,86.700,2.313,84.688,2.344,89.100,2.350,89.000,-13.766,889.942,76.981,0.296306
3,2019-01-01 00:45:00,2.654,78.160,2.494,74.939,2.574,87.267,2.808,82.733,-13.691,889.675,76.821,0.187590
4,2019-01-01 01:00:00,2.249,94.297,2.192,91.140,2.558,96.900,2.924,92.967,-13.447,890.025,74.571,0.081005
...,...,...,...,...,...,...,...,...,...,...,...,...,...
70171,2020-12-31 22:45:00,5.738,234.600,6.408,235.454,6.575,242.033,6.680,238.433,-9.108,890.008,53.312,13.633642
70172,2020-12-31 23:00:00,5.748,229.333,6.231,233.423,6.372,239.800,6.448,236.833,-9.978,889.817,53.877,6.869759
70173,2020-12-31 23:15:00,4.468,235.133,4.406,253.261,4.381,263.400,4.399,261.733,-9.808,889.825,54.437,4.352931
70174,2020-12-31 23:30:00,3.730,242.580,3.280,252.492,3.204,268.600,3.446,266.733,-9.633,889.492,54.677,7.185250
70175,2020-12-31 23:45:00,3.291,243.733,3.311,254.267,3.643,266.733,4.306,268.633,-8.991,889.492,53.381,12.384466

In [55]:
#dependent variable
y=dfcpy['Power']
y

0         0.254383
1         0.329703
2         0.296306
3         0.187590
4         0.081005
           ...
70171    13.633642
70172     6.869759
70173     4.352931
70174     7.185250
70175    12.384466
Name: Power, Length: 70176, dtype: float64

In [56]:
#independent variable
X=dfcpy.drop(columns=['Power','Time','Windspeed10m','Winddir10'],axis=1)
X.head()

,Windspeed30m,Winddir30,Wind speed at height of 50 meters (m/s),Wind direction at height of 50 meters (˚),Wind speed - at the height of wheel hub (m/s),Wind direction - at the height of wheel hub (˚),Air temperature (°C),Atmosphere (hpa),Relative humidity (%)
0,1.991,74.814,2.094,77.667,2.494,74.500,-13.484,889.867,76.320
1,1.698,75.048,1.757,88.733,1.882,74.367,-13.691,889.575,76.757
2,2.313,84.688,2.344,89.100,2.350,89.000,-13.766,889.942,76.981
3,2.494,74.939,2.574,87.267,2.808,82.733,-13.691,889.675,76.821
4,2.192,91.140,2.558,96.900,2.924,92.967,-13.447,890.025,74.571

In [57]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)
#0.3 indicates 30% test dataset and remaining 70% training dataset which is ideal size of dataset for ml algorithms training and testing

In [58]:
X_train

,Windspeed30m,Winddir30,Wind speed at height of 50 meters (m/s),Wind direction at height of 50 meters (˚),Wind speed - at the height of wheel hub (m/s),Wind direction - at the height of wheel hub (˚),Air temperature (°C),Atmosphere (hpa),Relative humidity (%)
63536,1.523,137.859,0.861,142.867,1.412,140.867,9.637,890.017,24.992
21654,4.646,292.855,5.020,298.733,5.605,296.467,31.287,889.467,10.667
2093,1.888,282.533,3.430,316.200,5.276,325.333,-6.734,889.533,61.360
61223,14.901,282.997,14.910,286.033,15.507,284.533,8.494,889.675,58.448
31193,11.646,257.968,12.232,262.367,12.430,258.833,-3.739,889.925,60.640
...,...,...,...,...,...,...,...,...,...
21243,8.028,214.812,7.453,218.833,6.667,215.633,21.352,889.583,20.891
45891,0.060,89.039,0.506,92.133,1.857,86.000,11.978,889.633,11.776
42613,5.846,258.673,6.221,264.933,6.434,262.133,10.316,889.817,41.109
43567,13.435,275.286,14.030,277.833,14.614,275.733,2.877,889.792,60.389
68268,9.143,256.757,9.553,257.983,9.709,251.083,-11.953,889.867,58.155

In [59]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [60]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor (n_estimators=20, random_state=0)
regressor.fit(X_train,y_train)

RandomForestRegressor(n_estimators=20, random_state=0)

In [61]:
y_pred=regressor.predict(X_test)
y_pred

array([33.8463498 , 26.1822845 ,  0.24315595, ...,  1.29827625,
        0.4281163 , 71.35506765])

In [62]:
Acc=pd.DataFrame({'Actual_y_value':y_test,'Predicted_y_value':y_pred})
Acc

       Actual_y_value  Predicted_y_value
50585       41.646313          33.846350
1610        26.752834          26.182285
68970        0.186879           0.243156
66444        1.792049           0.653117
38116        0.140692           0.487058
...               ...                ...
43785        7.865973           9.959906
34494       49.145634          50.389018
30848        1.079351           1.298276
33926        0.900288           0.428116
54458       84.859420          71.355068

[21053 rows x 2 columns]

In [63]:
from sklearn import metrics

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 5.144357317757993
Mean Squared Error: 72.07918619820266
Root Mean Squared Error: 8.489946183469167

In [64]:
from sklearn.model_selection import RandomizedSearchCV
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}
print(random_grid)

{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'max_features': ['auto', 'sqrt'], 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, None], 'min_samples_split': [2, 5, 10], 'min_samples_leaf': [1, 2, 4], 'bootstrap': [True, False]}

In [65]:
# Use the random grid to search for best hyperparameters
# First create the base model to tune
rf = RandomForestRegressor(n_estimators=10, random_state=0)
# Random search of parameters, using 3 fold cross validation, 
# search across different combinations, and use all available cores
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 3, cv = 3, verbose=2, random_state=4, n_jobs = -1)
# Fit the random search model
rf_random.fit(X_train, y_train)

Fitting 3 folds for each of 3 candidates, totalling 9 fits

/usr/local/lib/python3.7/dist-packages/joblib/externals/loky/process_executor.py:703: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  "timeout or by a memory leak.", UserWarning

RandomizedSearchCV(cv=3,
                   estimator=RandomForestRegressor(n_estimators=10,
                                                   random_state=0),
                   n_iter=3, n_jobs=-1,
                   param_distributions={'bootstrap': [True, False],
                                        'max_depth': [10, 20, 30, 40, 50, 60,
                                                      70, 80, 90, 100, 110,
                                                      None],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=4, verbose=2)

In [66]:
def evaluate(model, test_features, test_labels):
    predictions = model.predict(test_features)
    errors = abs(predictions - test_labels)
    mape = 100 * np.mean(errors / test_labels)
    accuracy = 100 - mape
    print('Model Performance')
    print('Average Error: {:0.4f} degrees.'.format(np.mean(errors)))
    print('Accuracy = {:0.2f}%.'.format(accuracy))
    
    return accuracy
base_model = regressor
base_accuracy = evaluate(base_model, X_test, y_test)

Model Performance
Average Error: 5.1444 degrees.
Accuracy = -inf%.

In [67]:
best_random = rf_random.best_estimator_
random_accuracy = evaluate(best_random, X_test, y_test)

Model Performance
Average Error: 4.9868 degrees.
Accuracy = -inf%.

In [68]:
from sklearn.metrics import r2_score

r2_score(y_test, y_pred)

0.8773928979826746