In [81]:
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [82]:
df= pd.read_excel('Windfarm.xlsx')
df.head()

,Time(year-month-day h:m:s),Wind speed at height of 10 meters (m/s),Wind direction at height of 10 meters (˚),Wind speed at height of 30 meters (m/s),Wind direction at height of 30 meters (˚),Wind speed at height of 50 meters (m/s),Wind direction at height of 50 meters (˚),Wind speed - at the height of wheel hub (m/s),Wind speed - at the height of wheel hub (˚),Air temperature (°C),Atmosphere (hpa),Relative humidity (%),Power (MW)
0,2019-01-01 00:00:00,2.209,81.317,1.991,74.814,2.094,77.667,2.494,74.500,-13.484,889.867,76.320,0.254383
1,2019-01-01 00:15:00,1.828,77.460,1.698,75.048,1.757,88.733,1.882,74.367,-13.691,889.575,76.757,0.329703
2,2019-01-01 00:30:00,2.193,86.700,2.313,84.688,2.344,89.100,2.350,89.000,-13.766,889.942,76.981,0.296306
3,2019-01-01 00:45:00,2.654,78.160,2.494,74.939,2.574,87.267,2.808,82.733,-13.691,889.675,76.821,0.187590
4,2019-01-01 01:00:00,2.249,94.297,2.192,91.140,2.558,96.900,2.924,92.967,-13.447,890.025,74.571,0.081005

In [90]:
#Checking for null values
df.isnull().any()

Time                                             False
Wind speed at height of 10 meters (m/s)          False
Wind direction at height of 10 meters (˚)        False
Wind speed at height of 30 meters (m/s)          False
Wind direction at height of 30 meters (˚)        False
Wind speed at height of 50 meters (m/s)          False
Wind direction at height of 50 meters (˚)        False
Wind speed - at the height of wheel hub (m/s)    False
Wind speed - at the height of wheel hub (˚)      False
Air temperature (°C)                             False
Atmosphere (hpa)                                 False
Relative humidity (%)                            False
Power                                            False
dtype: bool

In [84]:
#renaming a column name
df.rename(columns = {'Power (MW)':'Power'}, inplace = True)
df.rename(columns={'Time(year-month-day h:m:s)':'Time'},inplace = True)
df

,Time,Wind speed at height of 10 meters (m/s),Wind direction at height of 10 meters (˚),Wind speed at height of 30 meters (m/s),Wind direction at height of 30 meters (˚),Wind speed at height of 50 meters (m/s),Wind direction at height of 50 meters (˚),Wind speed - at the height of wheel hub (m/s),Wind speed - at the height of wheel hub (˚),Air temperature (°C),Atmosphere (hpa),Relative humidity (%),Power
0,2019-01-01 00:00:00,2.209,81.317,1.991,74.814,2.094,77.667,2.494,74.500,-13.484,889.867,76.320,0.254383
1,2019-01-01 00:15:00,1.828,77.460,1.698,75.048,1.757,88.733,1.882,74.367,-13.691,889.575,76.757,0.329703
2,2019-01-01 00:30:00,2.193,86.700,2.313,84.688,2.344,89.100,2.350,89.000,-13.766,889.942,76.981,0.296306
3,2019-01-01 00:45:00,2.654,78.160,2.494,74.939,2.574,87.267,2.808,82.733,-13.691,889.675,76.821,0.187590
4,2019-01-01 01:00:00,2.249,94.297,2.192,91.140,2.558,96.900,2.924,92.967,-13.447,890.025,74.571,0.081005
...,...,...,...,...,...,...,...,...,...,...,...,...,...
70171,2020-12-31 22:45:00,5.738,234.600,6.408,235.454,6.575,242.033,6.680,238.433,-9.108,890.008,53.312,13.633642
70172,2020-12-31 23:00:00,5.748,229.333,6.231,233.423,6.372,239.800,6.448,236.833,-9.978,889.817,53.877,6.869759
70173,2020-12-31 23:15:00,4.468,235.133,4.406,253.261,4.381,263.400,4.399,261.733,-9.808,889.825,54.437,4.352931
70174,2020-12-31 23:30:00,3.730,242.580,3.280,252.492,3.204,268.600,3.446,266.733,-9.633,889.492,54.677,7.185250
70175,2020-12-31 23:45:00,3.291,243.733,3.311,254.267,3.643,266.733,4.306,268.633,-8.991,889.492,53.381,12.384466

In [85]:
#dependent variable
y=df['Power']
y

0         0.254383
1         0.329703
2         0.296306
3         0.187590
4         0.081005
           ...
70171    13.633642
70172     6.869759
70173     4.352931
70174     7.185250
70175    12.384466
Name: Power, Length: 70176, dtype: float64

In [87]:
#independent variable
X=df.drop(columns=['Power','Time'],axis=1)
X.head()

,Wind speed at height of 10 meters (m/s),Wind direction at height of 10 meters (˚),Wind speed at height of 30 meters (m/s),Wind direction at height of 30 meters (˚),Wind speed at height of 50 meters (m/s),Wind direction at height of 50 meters (˚),Wind speed - at the height of wheel hub (m/s),Wind speed - at the height of wheel hub (˚),Air temperature (°C),Atmosphere (hpa),Relative humidity (%)
0,2.209,81.317,1.991,74.814,2.094,77.667,2.494,74.500,-13.484,889.867,76.320
1,1.828,77.460,1.698,75.048,1.757,88.733,1.882,74.367,-13.691,889.575,76.757
2,2.193,86.700,2.313,84.688,2.344,89.100,2.350,89.000,-13.766,889.942,76.981
3,2.654,78.160,2.494,74.939,2.574,87.267,2.808,82.733,-13.691,889.675,76.821
4,2.249,94.297,2.192,91.140,2.558,96.900,2.924,92.967,-13.447,890.025,74.571

In [88]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)
#0.3 indicates 30% test dataset and remaining 70% training dataset which is ideal size of dataset for ml algorithms training and testing

In [89]:
X_train

,Wind speed at height of 10 meters (m/s),Wind direction at height of 10 meters (˚),Wind speed at height of 30 meters (m/s),Wind direction at height of 30 meters (˚),Wind speed at height of 50 meters (m/s),Wind direction at height of 50 meters (˚),Wind speed - at the height of wheel hub (m/s),Wind speed - at the height of wheel hub (˚),Air temperature (°C),Atmosphere (hpa),Relative humidity (%)
63536,1.631,169.873,1.523,137.859,0.861,142.867,1.412,140.867,9.637,890.017,24.992
21654,4.767,294.853,4.646,292.855,5.020,298.733,5.605,296.467,31.287,889.467,10.667
2093,1.602,259.433,1.888,282.533,3.430,316.200,5.276,325.333,-6.734,889.533,61.360
61223,13.250,288.053,14.901,282.997,14.910,286.033,15.507,284.533,8.494,889.675,58.448
31193,10.090,235.367,11.646,257.968,12.232,262.367,12.430,258.833,-3.739,889.925,60.640
...,...,...,...,...,...,...,...,...,...,...,...
21243,7.177,219.620,8.028,214.812,7.453,218.833,6.667,215.633,21.352,889.583,20.891
45891,1.383,180.110,0.060,89.039,0.506,92.133,1.857,86.000,11.978,889.633,11.776
42613,4.724,249.713,5.846,258.673,6.221,264.933,6.434,262.133,10.316,889.817,41.109
43567,12.263,244.300,13.435,275.286,14.030,277.833,14.614,275.733,2.877,889.792,60.389
68268,7.835,264.867,9.143,256.757,9.553,257.983,9.709,251.083,-11.953,889.867,58.155

In [91]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [92]:
from sklearn.svm import SVR

# Choose regression method and set hyperparameter
svr_rbf=SVR(C=1.0, epsilon=0.2, kernel='rbf')

# Training of the regression model
svr_rbf.fit(X_train, y_train)
y_pred = svr_rbf.predict(X_test)

In [95]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

mean_squared_error(y_test, y_pred)

90.12940029445915

In [96]:
mean_absolute_error(y_test, y_pred)

5.671437361584176

In [97]:
from sklearn.metrics import r2_score

r2_score(y_test, y_pred)

0.8466893820599397